# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Website/Website" # Location of package.json
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Website/Packages/datax-common" # Location of package.json
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Website/Packages/datax-home" # Location of package.json
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/DataProcessing/datax-core" # Location of pom.xml
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/DataProcessing/datax-host" # Location of pom.xml
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/DataProcessing/datax-keyvault" # Location of pom.xml
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/DataProcessing/datax-utility" # Location of pom.xml
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Services" # Location of package manifests
    schedule:
      interval: "weekly"
